# create a docker-compose file with redis
# + api and worker image built from the Dockerfile
version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: uvicorn api:app --host 0.0.0.0 --port 8000

  worker:
    build: .
    depends_on:
      - redis
    command: rq worker --url redis://rq_redis:6379 order_queue

  redis:
    container_name: rq_redis
    image: redis:latest
    ports:
      - "6379:6379"
